# Generated by Django 4.2.28 on 2026-02-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_item_alter_profile_options_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header_bg_color',
            field=models.CharField(default='#f8f9fa', max_length=7, verbose_name='背景颜色'),
        ),
        migrations.AddField(
            model_name='profile',
            name='header_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='header_bg/', verbose_name='背景图片'),
        ),
        migrations.AddField(
            model_name='profile',
            name='header_bg_type',
            field=models.CharField(choices=[('color', '纯色'), ('image', '图片')], default='color', max_length=10, verbose_name='背景类型'),
        ),
    ]
