# Generated by Django 4.2.28 on 2026-02-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_header_bg_color_profile_header_bg_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='header_bg_color',
            field=models.CharField(default='#808080', max_length=7, verbose_name='背景颜色'),
        ),
    ]
