# Generated by Django 4.2.28 on 2026-02-28 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='物品标题')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('trade_method', models.CharField(choices=[('face_to_face', '面交'), ('shipping', '邮寄'), ('both', '均可')], default='face_to_face', max_length=20, verbose_name='交易方式')),
                ('contact', models.CharField(max_length=100, verbose_name='联系方式')),
                ('condition', models.CharField(choices=[('new', '全新'), ('used', '二手'), ('idle', '闲置')], default='used', max_length=20, verbose_name='物品状态')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='物品图片')),
                ('status', models.CharField(choices=[('active', '在售'), ('sold', '已售'), ('inactive', '下架')], default='active', max_length=20, verbose_name='物品状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category', verbose_name='物品分类')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='items_item_created_3eaa9f_idx'), models.Index(fields=['category'], name='items_item_categor_ac6954_idx'), models.Index(fields=['status'], name='items_item_status_819478_idx')],
            },
        ),
    ]
