# Generated by Django 4.2.28 on 2026-02-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='精确价格（元）'),
        ),
        migrations.AddField(
            model_name='item',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='价格区间（如：50-100）'),
        ),
    ]
