# Generated by Django 4.2.28 on 2026-02-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_price_item_price_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_range',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(default='面议', help_text='支持精确值（如：100）或区间（如：50-100），单位：元', max_length=50, verbose_name='价格'),
        ),
    ]
